#!/bin/sh
#
# This is a package managfer agnostic helper to install package(s).
#

set -e # Exit immediately if a command exits with a non-zero status.

usage() {
    echo "usage: $(basename "$0") [--virtual NAME ] PKG [PKG...]" >&2
    exit 1
}

die() {
    echo "ERROR: $*" >&2
    exit 1
}

trap : TERM QUIT INT
trap "cleanup" EXIT

#
# APK functions
#

is_pkg_installed_apk() {
    apk -e info "$1" > /dev/null
}

install_pkg_apk() {
    VIRTUAL_PKG="$1"
    shift

    if [ "${VIRTUAL_PKG}" -eq 1 ]; then
        set -- "--virtual" "$@"
    fi

    apk --no-cache add "$@"
}

cleanup_apk() {
    rm -rf /var/cache/misc/*
}

#
# APT functions
#

is_pkg_installed_apt() {
    dpkg --status "$1" 2>&1 | grep -q "^Status: install ok installed"
}

install_pkg_apt() {
    VIRTUAL_PKG="$1"
    shift

    if [ "${VIRTUAL_PKG}" -eq 1 ]; then
        VIRTUAL_PKG_NAME=$1
        shift

        if [ -f "/var/lib/apt/${VIRTUAL_PKG_NAME}.virtual" ]; then
            die "Virtual package '${VIRTUAL_PKG_NAME}' already exists."
        fi

        echo "$*" > "/var/lib/apt/${VIRTUAL_PKG_NAME}.virtual"
    fi

    if [ -n "$1" ]; then
        apt-get -q update
        apt-get -q install -y --no-install-recommends "$@"
    fi
}

cleanup_apt() {
    apt-get -q clean
    rm -rf /var/lib/apt/lists/* \
        /var/log/dpkg.log \
        /var/log/alternatives.log \
        /var/log/apt/*
}

#
# Package manager agnostic functions
#

is_pkg_installed() {
    if command -v apk > /dev/null; then
        is_pkg_installed_apk "$@"
    else
        is_pkg_installed_apt "$@"
    fi
}

install_pkg() {
    if command -v apk > /dev/null; then
        install_pkg_apk "$@"
    else
        install_pkg_apt "$@"
    fi
}

cleanup() {
    if command -v apk > /dev/null; then
        cleanup_apk
    else
        cleanup_apt
    fi
}

#
# Main
#

if [ -z "$1" ]; then
    usage
fi

if command -v apt > /dev/null; then
    export DEBIAN_FRONTEND=noninteractive
fi

VIRTUAL_PKG=
if [ "$1" = "--virtual" ]; then
    shift
    if [ -z "$1" ]; then
        echo "Virtual package name missing."
        usage
    fi
    VIRTUAL_PKG="$1"
    shift
fi

if [ -n "${VIRTUAL_PKG}" ]; then
    pkgs="${VIRTUAL_PKG}"
    for pkg in "$@"; do
        if ! is_pkg_installed "${pkg}"; then
            pkgs="${pkgs} ${pkg}"
        fi
    done
    # shellcheck disable=2086
    install_pkg 1 ${pkgs}
else
    install_pkg 0 "$@"
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
