#!/bin/sh
#
# This is a package manager agnostic helper to check if a package is installed.
#

set -e # Exit immediately if a command exits with a non-zero status.

usage() {
    echo "usage: $(basename "$0") PKG [PKG...]" >&2
    exit 1
}

#
# APK functions
#

check_pkg_apk() {
    apk -e info "$1" > /dev/null
}

#
# APT functions
#

check_pkg_apt() {
    dpkg --status "$1" 2>&1 | grep -q "^Status: install ok installed"
}

#
# Package manager agnostic functions
#

check_pkg() {
    for pkg in "$@"; do
        if command -v apk > /dev/null; then
            check_pkg_apk "${pkg}"
        else
            check_pkg_apt "${pkg}"
        fi
    done
}

#
# Main
#

if [ -z "$1" ]; then
    usage
fi

if command -v apt > /dev/null; then
    export DEBIAN_FRONTEND=noninteractive
fi

check_pkg "$@"

# vim:ft=sh:ts=4:sw=4:et:sts=4
