#!/bin/sh

#
# APK functions
#

init_env_apk() {
    # Nothing to do.
    :
}

cleanup_env_apk() {
    find /etc -name "*.apk-new" -delete
    rm -rf \
        /var/cache/misc/* \
        /var/log/apk.log
}

#
# APT functions
#

init_env_apt() {
    # Some package installation scripts require the log folder to exist, along
    # with user and group database files. These might not exist when this script
    # is used to build containers.

    [ -d /config ] || {
        mkdir /config
        touch /tmp/.config.created
    }
    [ -d /config/log ] || {
        mkdir /config/log
        touch /tmp/.config.log.created
    }

    [ -d /tmp/run ] || {
        mkdir /tmp/run
        touch /tmp/.tmp.run.created
    }

    if [ ! -f /etc/passwd ] && [ ! -f /etc/group ] && [ ! -f /etc/shadow ] && [ ! -f /etc/gshadow ]
    then
        /etc/cont-init.d/10-init-users.sh
        touch /tmp/.user-group-database.created
    fi
}

cleanup_env_apt() {
    apt-get -q clean
    rm -rf \
        /var/cache/apt/* \
        /var/cache/debconf/* \
        /var/lib/apt/lists/* \
        /var/log/dpkg.log \
        /var/log/alternatives.log \
        /var/log/apt/*
    [ ! -f /tmp/.user-group-database.created ] || {
        rm -f \
            /tmp/.passwd \
            /tmp/.group \
            /tmp/.shadow \
            /tmp/.gshadow \
            /tmp/.user-group-database.created
    }
    [ ! -f /tmp/.config.log.created ] || {
        rm -rf \
            /config/log \
            /tmp/.config.log.created
    }
    [ ! -f /tmp/.config.created ] || {
        rm -rf \
            /config \
            /tmp/.config.created
    }
    [ ! -f /tmp/.tmp.run.created ] || {
        rm -rf \
            /tmp/run \
            /tmp/.tmp.run.created
    }
    [ ! -f /tmp/.passwd.created ] || {
        rm -rf \
            /tmp/.passwd \
            /tmp/.passwd.created
    }
    [ ! -f /tmp/.group.created ] || {
        rm -rf \
            /tmp/.group \
            /tmp/.group.created
    }
    [ ! -f /tmp/.shadow.created ] || {
        rm -rf \
            /tmp/.shadow \
            /tmp/.shadow.created
    }
    [ ! -f /tmp/.gshadow.created ] || {
        rm -rf \
            /tmp/.gshadow \
            /tmp/.gshadow.created
    }
}

#
# Package manager agnostic functions
#

init_env() {
    if command -v apk > /dev/null; then
        init_env_apk "$@"
    else
        init_env_apt "$@"
    fi
}

cleanup_env() {
    if command -v apk > /dev/null; then
        cleanup_env_apk "$@"
    else
        cleanup_env_apt "$@"
    fi
}

# vim:ft=sh:ts=4:sw=4:et:sts=4
