#!/bin/sh
#
# This is a package manager agnostic helper to remove installed package(s).
#

set -e # Exit immediately if a command exits with a non-zero status.

usage() {
    echo "usage: $(basename "$0") PKG [PKG...]" >&2
    exit 1
}

#
# APK functions
#

del_pkg_apk() {
    apk --no-cache --purge del "$@"
    rm -rf /var/cache/misc/*
}

#
# APT functions
#

del_pkg_apt() {
    pkgs=
    for pkg in "$@"; do
        if ! dpkg --status "$1" 2>&1 | grep -q "^Status: install ok installed"; then
            if [ -f "/var/lib/apt/${pkg}.virtual" ]; then
                pkgs="${pkgs} $(cat "/var/lib/apt/${pkg}.virtual")"
                rm "/var/lib/apt/${pkg}.virtual"
            else
                pkgs="${pkgs} ${pkg}"
            fi
        else
            pkgs="${pkgs} ${pkg}"
        fi
    done

    if [ -n "${pkgs}" ]; then
        # shellcheck disable=2086
        apt-get -q purge -y ${pkgs}
        apt-get -q --purge autoremove -y
        rm -rf /var/log/dpkg.log \
            /var/log/apt/*
    fi
}

#
# Package manager agnostic functions
#

del_pkg() {
    if command -v apk > /dev/null; then
        del_pkg_apk "$@"
    else
        del_pkg_apt "$@"
    fi
}

#
# Main
#

if [ -z "$1" ]; then
    usage
fi

if command -v apt > /dev/null; then
    export DEBIAN_FRONTEND=noninteractive
fi

del_pkg "$@"

# vim:ft=sh:ts=4:sw=4:et:sts=4
