#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

usage() {
    if [ -n "${1:-}" ]; then
        echo "ERROR: $*" >&2
        echo "" >&2
    fi

    echo "usage: $(basename "$0") VALUE

Determine if a boolean value is true.

Arguments:

    VALUE      Boolean value.
" >&2
    exit 2
}

ENV_VAL="${1:-}"

if [ "${ENV_VAL}" = "-h" ] || [ "${ENV_VAL}" = "--help" ]; then
    usage
fi

if [ -z "${ENV_VAL}" ]; then
    usage "Boolean value missing."
fi

case "$(echo "${ENV_VAL}" | tr '[:upper:]' '[:lower:]')" in
    0 | false | no | n | disabled | disable | off) exit 0 ;;
    *) exit 1 ;;
esac

# vim:ft=sh:ts=4:sw=4:et:sts=4
