#!/bin/sh

#
# Add an environment variable to /etc/cont-env.d
#

set -e # Exit immediately if a command exits with a non-zero status.

usage() {
    echo "usage: $(basename "$0") ENV=[VAL]"
}

valid_var_name() {
    case "$1" in
        *[!a-zA-Z0-9_]*|[0-9]*)
            return 1
            ;;
        *)
            return 0
            ;;
    esac
}

if [ $# -ne 1 ]; then
    usage
    exit 1
fi

case "$1" in
    *=*) ;;
    *)
        echo "ERROR: Invalid environment variable format."
        exit 1
        ;;
esac

NAME="$(echo "$1" | cut -d'=' -f1)"
VAR="$(echo "$1" | cut -d'=' -f2)"

if ! valid_var_name "$NAME"; then
    echo "ERROR: Invalid environment variable name '$NAME'."
    exit 1
fi

echo "$VAR" > /etc/cont-env.d/$NAME

# vim:ft=sh:ts=4:sw=4:et:sts=4
