#!/bin/sh
#
# Add/set an environment variable to /etc/cont-env.d.
#

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

usage() {
    if [ -n "${1:-}" ]; then
        echo "ERROR: $*" >&2
        echo "" >&2
    fi

    echo "usage: $(basename "$0") NAME [VALUE]

Save a container environment variable.

Arguments:

    NAME       Name of the environment variable.
    VALUE      Value of the environment variable.
" >&2
    exit 1
}

die() {
    echo "ERROR: $*" >&2
    exit 1
}

valid_env_var_name() {
    case "$1" in
        *[!A-Z0-9_]* | [0-9]*)
            return 1
            ;;
        *)
            return 0
            ;;
    esac
}

ENV_NAME="${1:-}"
ENV_VAL="${2:-}"

if [ "${ENV_NAME}" = "-h" ] || [ "${ENV_NAME}" = "--help" ]; then
    usage
fi

if [ -z "${ENV_NAME}" ]; then
    usage "Name of the environment variable missing."
fi

if ! valid_env_var_name "${ENV_NAME}"; then
    die "Invalid environment variable name."
fi

# Write the environment variable.
printf "%s" "${ENV_VAL}" > /etc/cont-env.d/"${ENV_NAME}"

# vim:ft=sh:ts=4:sw=4:et:sts=4
