#!/bin/sh
#
# This is a package manager agnostic helper to upgrade package(s).
#

set -e # Exit immediately if a command exits with a non-zero status.

usage() {
    echo "usage: $(basename "$0") [PKG...]" >&2
    exit 1
}

die() {
    echo "ERROR: $*" >&2
    exit 1
}

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "${SCRIPT_DIR}/cmn-pkg"

trap : TERM QUIT INT
trap "cleanup_env" EXIT

#
# APK functions
#

upgrade_pkg_apk() {
    apk --no-cache upgrade "$@"
}

#
# APT functions
#

upgrade_pkg_apt() {
    apt-get -q update
    if [ -n "$1" ]; then
        apt-get -q install -y --no-install-recommends --only-upgrade "$@"
    else
        apt-get -q upgrade -y
    fi
    apt-get -q autoremove -y --purge
}

#
# Package manager agnostic functions
#

upgrade_pkg() {
    init_env
    if command -v apk > /dev/null; then
        upgrade_pkg_apk "$@"
    else
        upgrade_pkg_apt "$@"
    fi
}

#
# Main
#

if command -v apt-get > /dev/null; then
    export DEBIAN_FRONTEND=noninteractive
    export LC_ALL=C
fi

if [ $# -eq 1 ] && [ "${1}" = "all" ]; then
    shift
fi
upgrade_pkg "$@"

# vim:ft=sh:ts=4:sw=4:et:sts=4
