#!/usr/bin/with-contenv sh
#
# This is the finish script of the 'app' service.  It determines if the 'app'
# service needs to be restarted or not.  If not, the container is shutted down.
#
# NOTE: It is expected that the 'app' service is NOT restarted automatically by
#       minit (i.e. the 'app' service doesn't have the 'respawn' flag).
#

set -u # Treat unset variables as an error.

# Nothing to do if the container is shutting down.
if [ -f /var/run/cont-env/CONTAINER_IS_SHUTTING_DOWN ]; then
    exit
fi

APP_RC="$1"

# App terminated: Bring container down if needed.
if [ "${KEEP_GUIAPP_RUNNING:-0}" -eq "0" ] && [ "${KEEP_APP_RUNNING:-0}" -eq "0" ]; then
    # Use the forced exit code if needed.
    echo ${FORCE_APP_EXIT_CODE:-$APP_RC} > /var/run/cont-env/CONTAINER_EXIT_CODE
    sync

    # Bring the container down.
    # NOTE: Make sure to run the command in background to not block indefinitely.
    msvc -o shutdown &
else
    # Restart the app.
    sleep 2
    msvc -o app &
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
