#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

if [ "${KEEP_APP_RUNNING:-0}" -eq 0 ]; then
    if [ -n "${FORCE_APP_EXIT_CODE:-}" ]; then
        add-contenv "FORCED_CONTAINER_EXIT_CODE" "$FORCE_APP_EXIT_CODE"
    fi
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
