#!/usr/bin/with-contenv sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

[ "${DISABLE_APP:-0}" -eq 0 ]

# vim:ft=sh:ts=4:sw=4:et:sts=4
