#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

if [ "${KEEP_APP_RUNNING:-0}" -eq 0 ]; then
    echo "false"
else
    echo "true"
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
