#!/bin/sh

set -u # Treat unset variables as an error.

echo "starting ${APP_NAME:-Docker application}..."
if [ -x /startapp.sh ]; then
    # Start the application.
    exec 2>&1 /startapp.sh
else
    echo "/!\\ No application to start: /startapp.sh is missing or not executable. /!\\"
    # Make sure the container exits with an error code.
    exit 5
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
