#!/usr/bin/with-contenv sh

set -u # Treat unset variables as an error.

echo "[$(basename "$(pwd)")] starting "${APP_NAME:-Docker application}"..."
if [ -e /startapp.sh ]; then 
    # Set the umask.
    if [ "${UMASK:-UNSET}" != "UNSET" ]; then
        umask "$UMASK"
    fi

    # Start the application.
    # NOTE: su-exec will take the proper group ID and supplementary groups from
    #       /etc/group.
    exec su-exec "$USER_ID" /startapp.sh
else
    echo ""
    echo "/!\\ No application to start: /startapp.sh is missing. /!\\"
    echo ""
    # Make sure the container exits with an error code.
    exit 5
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
