#!/bin/sh

set -u # Treat unset variables as an error.

if [ -x /startapp.sh ]; then
    # Start the application.
    exec /startapp.sh "$@"
else
    echo "/!\\ No application to start: /startapp.sh is missing or not executable. /!\\"
    # Make sure the container exits with an error code.
    exit 5
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
