#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

grps="${SUP_GROUP_IDS:-},${SUP_GROUP_IDS_INTERNAL:-}"

# Check the environment for SUP_GROUP_IDS_INTERNAL_* variables.
for var in $(env | sed -n 's/\(^SUP_GROUP_IDS_INTERNAL_[A-Z0-9_]\+\)\=.*/\1/p'); do
    eval "grps=\${grps},\$${var}"
done

echo "${grps}" \
    | tr ',' '\n' \
    | grep -v '^$' \
    | grep -v '^0$' \
    | grep -vw "${GROUP_ID}" \
    | sort -nub

# vim:ft=sh:ts=4:sw=4:et:sts=4
