#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

TITLE="$1"
MSG="$2"
LEVEL="$3"

echo "$LEVEL: $TITLE $MSG"

# vim:ft=sh:ts=4:sw=4:et:sts=4
