#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

if grep -q 'LOG_FILES=/.\+' /etc/logmonitor/logmonitor.conf || grep -q 'STATUS_FILES=/.\+' /etc/logmonitor/logmonitor.conf; then
    echo "false"
else
    # No file to be monitored.  Service should be disabled.
    echo "true"
fi 

# vim:ft=sh:ts=4:sw=4:et:sts=4
