#!/usr/bin/with-contenv sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

# Load the logmonitor configuration file.
. /etc/logmonitor/logmonitor.conf

# Check if at least one file is set.
if [ "${LOG_FILES:-UNSET}" != "UNSET" ] || [ "${STATUS_FILES:-UNSET}" != "UNSET" ]
then
    exit 0
else
    echo "no file to monitor."
    exit 1
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
