#!/usr/bin/with-contenv sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

# Load the logmonitor configuration file.
. /etc/logmonitor/logmonitor.conf

CMD="exec /usr/bin/logmonitor"

if [ "${LOG_FILES:-UNSET}" != "UNSET" ]; then
    ORIG_IFS="$IFS"
    IFS=","
    for FILE in $LOG_FILES
    do
        CMD="$CMD \"$FILE\""
    done
    IFS="$ORIG_IFS"
fi

if [ "${STATUS_FILES:-UNSET}" != "UNSET" ]; then
    ORIG_IFS="$IFS"
    IFS=","
    for FILE in $STATUS_FILES
    do
        CMD="$CMD \"$FILE\""
    done
    IFS="$ORIG_IFS"
fi

eval "$CMD"

# vim:ft=sh:ts=4:sw=4:et:sts=4
